Resources:
  # ---------------------
  # PrivateRouteTable
  # ---------------------
  PrivateRouteTable0:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-private-route-table0

  PrivateRouteTable1:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-private-route-table1

  PrivateRouteTable2:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-private-route-table2

  # -----------------------------------
  # PrivateSubnetRouteTableAssociation
  # -----------------------------------
  PrivateSubnetRouteTableAssociation0:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnet0
      RouteTableId: !Ref PrivateRouteTable0

  PrivateSubnetRouteTableAssociation1:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnet1
      RouteTableId: !Ref PrivateRouteTable1

  PrivateSubnetRouteTableAssociation2:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnet2
      RouteTableId: !Ref PrivateRouteTable2

Outputs:
  PrivateRouteTable0:
    Description: "route table of private subnet0"
    Value: !Ref PrivateRouteTable0
    Export:
      Name: !Sub "${AWS::Region}-${AWS::StackName}-PrivateRouteTable0"

  PrivateRouteTable1:
    Description: "route table of private subnet1"
    Value: !Ref PrivateRouteTable1
    Export:
      Name: !Sub "${AWS::Region}-${AWS::StackName}-PrivateRouteTable1"

  PrivateRouteTable2:
    Description: "route table of private subnet2"
    Value: !Ref PrivateRouteTable2
    Export:
      Name: !Sub "${AWS::Region}-${AWS::StackName}-PrivateRouteTable2"