Resources:
  # ---------------------
  # VPC
  # ---------------------
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !FindInMap [SubnetConfig, VPC, CIDR]
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-vpc

Outputs:
  VPCId:
    Description: "vpc id of vpc"
    Value: !Ref VPC
    Export:
      Name: !Sub "${AWS::Region}-${AWS::StackName}-VPC"
  AZs:
    Value: !Join [ ", ", Fn::GetAZs: !Ref "AWS::Region" ]
