Mappings:
  SubnetConfig:
    VPC:
      CIDR: "10.0.0.0/16"
    PublicSubnet0:
      CIDR: "10.0.0.0/24"
    PublicSubnet1:
      CIDR: "10.0.1.0/24"
    PublicSubnet2:
      CIDR: "10.0.2.0/24"
    PrivateSubnet0:
      CIDR: "10.0.3.0/24"
    PrivateSubnet1:
      CIDR: "10.0.4.0/24"
    PrivateSubnet2:
      CIDR: "10.0.5.0/24"
    EC2Instance:
      ImageId: ami-09ebacdc178ae23b7
      InstanceType: t3.micro

